// <auto-generated />
using System;
using Awoo.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Awoo.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230706121808_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Awoo.Shared.Availibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Availibility");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2023, 7, 6, 13, 18, 8, 35, DateTimeKind.Local).AddTicks(8558),
                            Duration = new TimeSpan(2, 0, 0, 0, 0),
                            PlayerId = 1,
                            State = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = new TimeSpan(2, 0, 0, 0, 0),
                            PlayerId = 2,
                            State = (byte)0
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            Duration = new TimeSpan(2, 0, 0, 0, 0),
                            PlayerId = 3,
                            State = (byte)2
                        });
                });

            modelBuilder.Entity("Awoo.Shared.TTRPG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Colour")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TTRPGs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colour = -65536,
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            Id = 2,
                            Colour = -23296,
                            Name = "Pathfinder 2e"
                        },
                        new
                        {
                            Id = 3,
                            Colour = -16776961,
                            Name = "Dungeons And Dragons"
                        });
                });

            modelBuilder.Entity("Awoo.Shared.TabletopSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GameMasterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextSession")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameMasterId");

                    b.ToTable("TabletopSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            GameMasterId = 3,
                            Name = "Cyberpunk Sunday",
                            NextSession = new DateTime(2023, 7, 6, 13, 18, 8, 35, DateTimeKind.Local).AddTicks(8480)
                        },
                        new
                        {
                            Id = 2,
                            GameId = 2,
                            GameMasterId = 3,
                            Name = "Pathfinder Saturdays",
                            NextSession = new DateTime(2023, 7, 6, 13, 18, 8, 35, DateTimeKind.Local).AddTicks(8540)
                        },
                        new
                        {
                            Id = 3,
                            GameId = 3,
                            GameMasterId = 3,
                            Name = "Dungeons And Dragons Fridays",
                            NextSession = new DateTime(2023, 7, 6, 13, 18, 8, 35, DateTimeKind.Local).AddTicks(8544)
                        });
                });

            modelBuilder.Entity("Awoo.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Colour")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TabletopSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TabletopSessionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Colour = -2354116,
                            Password = "",
                            Username = "Cali"
                        },
                        new
                        {
                            Id = 2,
                            Colour = -16728065,
                            Password = "",
                            Username = "Bali"
                        },
                        new
                        {
                            Id = 3,
                            Colour = -1644806,
                            Password = "",
                            Username = "foreverDM"
                        });
                });

            modelBuilder.Entity("Awoo.Shared.Availibility", b =>
                {
                    b.HasOne("Awoo.Shared.User", "Player")
                        .WithMany("Schedule")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Awoo.Shared.TabletopSession", b =>
                {
                    b.HasOne("Awoo.Shared.TTRPG", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Awoo.Shared.User", "GameMaster")
                        .WithMany()
                        .HasForeignKey("GameMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameMaster");
                });

            modelBuilder.Entity("Awoo.Shared.User", b =>
                {
                    b.HasOne("Awoo.Shared.TabletopSession", null)
                        .WithMany("Players")
                        .HasForeignKey("TabletopSessionId");
                });

            modelBuilder.Entity("Awoo.Shared.TabletopSession", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Awoo.Shared.User", b =>
                {
                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
